version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    env_file:
          - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"